#!/bin/bash
if [ ! -n "$BASH_VERSION" ];then exec bash "$0" "$@";else set +o posix;fi

rm -rf demoCA certs
mkdir certs

# Default insecurity
case "$1" in
*.pfx )
    PFX="$1"
    shift
    ;;
* ) PFX=domain-key.pfx
    PASS=0000
    ;;
esac

# Copy CA key
openssl pkcs12 -nodes ${PASS:+-passin pass:$PASS} -in "$PFX" -out certs/ca.pem
if [ "$PASS" != "" ]
then openssl pkcs12 -nodes ${PASS:+-passin pass:$PASS} -in "$PFX" -out certs/ca.crt -nokeys
else openssl x509 -in certs/ca.pem -out certs/ca.crt
fi

if [ "$#" -gt 0 ]
then
    for host
    do sh cmd.02.make-crt ${host//,/ } || break
    done
fi
