#!/bin/bash
if [ ! -n "$BASH_VERSION" ];then exec bash "$0" "$@";else set +o posix;fi

export OPENSSL_CONF=/dev/null
CERT_DIR="${CERT_DIR:-certs}"

[ -s "$CERT_DIR"/ca.pem ] && { echo ERROR: CA already exists ; exit 1 ; }
mkdir -p "$CERT_DIR"

# Default insecurity
case "$1" in
*.pfx )
    PFX="$1"
    shift
    ;;
* ) PFX=domain-key.pfx
    PASS=0000
    ;;
esac

# Copy CA key
openssl pkcs12 -nodes ${PASS:+-passin pass:$PASS} -in "$PFX" -out "$CERT_DIR"/ca.pem ||
    exit

if [ "$#" -gt 0 ]
then
    export CRLURL=http://tvtdc00.tvt.local/CertEnroll/TVision%20Domain.crl

    for host
    do sh cmd.02.make-crt ${host//,/ } || break
    done
fi
