#!/bin/bash -
if [ ! -n "$BASH_VERSION" ];then exec bash "$0" "$@";else set +o posix;fi
set -e

if [ "$#" -lt 1 ]
then
    echo >&2 "Usage: $0: commonName"
    exit 1
fi

CN="$1"

# working_signed_by_domain
bash mk-self-sign \
    -rsa \
    "$@" \
    -sign=domain-key.pfx \
    -v3="crlDistributionPoints=URI:http://TVTDC00.tvt.local/CertEnroll/TVision%20Domain.crl" \

exit

# Working self-sign
# bash mk-self-sign -rsa "$CN"

# Extra crap on pattern
    -rsa:1024 -sha1 \
    -v3="extendedKeyUsage = serverAuth" \
    -v3="keyUsage = keyEncipherment,digitalSignature" \
    -v3="subjectKeyIdentifier=hash" \
    -v3="subjectAltName=DNS:$CN" \
    -v3="authorityKeyIdentifier=keyid,issuer" \
