#!/bin/sh
set -e

if [ "$#" -lt 1 ]
then
    echo >&2 "Usage: $0: commonName"
    exit 1
fi

# working_signed_by_domain
bash mk-cert \
    -rsa \
    -sign=domain-key.pfx \
    -v3="crlDistributionPoints=URI:http://TVTDC00.tvt.local/CertEnroll/TVision%20Domain.crl" \
    "$@"
