#!/bin/bash -
if [ ! -n "$BASH_VERSION" ];then exec bash "$0" "$@";else set +o posix;fi
set -e

mkkey() { openssl ecparam -name prime256v1 -genkey -out "$1" ;}
V3OPTS=
V3INIT='x509_extensions = req_x509
[ req_x509 ]
'

for ar
do  case "$ar" in
    /*=* ) SUBJ="$ar" ;;
    -days=* ) CERT_DAYS=${ar#*=} ;;
    -ca ) FN=ca ;;
    -out=* ) FN="${ar#*=}" ;;

    -rsa ) eval "mkkey() { openssl genrsa -out \"\$1\" 3072 ; }" ;;
    -rsa=* ) eval "mkkey() { openssl genrsa -out \"\$1\" ${ar#*=} ; }" ;;
    -dsa ) eval "mkkey() { openssl dsaparam -genkey -out \"\$1\" 3072 ; }" ;;
    -dsa=* ) eval "mkkey() { openssl dsaparam -genkey -out \"\$1\" ${ar#*=} ; }" ;;
    -ec ) eval "mkkey() { openssl ecparam -name prime256v1 -genkey -out \"\$1\" ; }" ;;
    -ec=* ) eval "mkkey() { openssl ecparam -name ${ar#*=} -genkey -out \"\$1\" ; }" ;;

    -md4|-md5|-ripemd160|-sha|-sha1|-sha224|-sha256|-sha384|-sha512|-whirlpool)
	DGST=$ar ;;

    -v3=* ) [ "$V3OPTS" = "" ] && V3OPTS="$V3INIT"
	    V3OPTS="$V3OPTS
	    ${ar#*=}
	    "
	    ;;

    -v3ca ) [ "$V3OPTS" = "" ] && V3OPTS="$V3INIT"
	    FN=ca
	    V3OPTS="$V3OPTS
	    subjectKeyIdentifier=hash
	    authorityKeyIdentifier=keyid:always,issuer
	    basicConstraints = CA:true
	    "
	    ;;

    -*|*/*) echo >&2 "Unknown option: $ar" ; exit 1 ;;
    * ) SUBJ="/CN=$ar/" ; CN="$ar";;
    esac
done
# openssl genpkey -paramfile <(openssl genpkey -genparam -algorithm ec -pkeyopt ec_paramgen_curve:prime256v1) -out "$CAKEY"

[ "$FN" = "" ] && {
    [ "$CN" = "" ] && { CN="${SUBJ/*\/CN=/}" ; CN="${CN/\/*/}"; }
    FN="$CN"
    case "$FN" in \*.* ) FN=${FN#??} ;; esac
    FN="${FN:-ca}"
}

umask 077
mkdir -p certs 
CAKEY=certs/"$FN.key"
CACRT=certs/"$FN.crt"
CAPEM=certs/"$FN.pem"

[ -s "$CAPEM" -o -s "$CAKEY" ] &&
    { echo ERROR: File $CAPEM or .key already exists ; exit 1 ; }

mkkey "$CAKEY"
openssl req -new -x509 $DGST -days "${CERT_DAYS:-3652}" \
    ${SUBJ:+-subj "$SUBJ"} \
    -key "$CAKEY" -out "$CACRT" -config <(echo '
[req]
distinguished_name = req_distinguished_name
'"$V3OPTS"'
[ req_distinguished_name ]
organizationalUnitName = Organizational Unit Name
commonName = Common Name' )

{
    openssl x509 -subject -serial -dates -in "$CACRT"
    openssl pkey -in "$CAKEY"
}> "$CAPEM"
