#!/bin/bash -
if [ ! -n "$BASH_VERSION" ];then exec bash "$0" "$@";else set +o posix;fi
set -e
export OPENSSL_CONF=/dev/null
CERT_DIR="${CERT_DIR:-.}"

# This is my default for making a key file.
mkkey() { openssl ecparam -name prime256v1 -genkey ;}
# See also:
# mkkey() { openssl genpkey -paramfile <(openssl genpkey -genparam -algorithm ec -pkeyopt ec_paramgen_curve:prime256v1) ;}

FN=
V3OPTS=
V3EXTRAS=
V3INIT='x509_extensions = req_x509
[ req_x509 ]
'

for ar
do  case "$ar" in
    /*=* )
	if [ "$SUBJ" != "" ] ; then
	    echo >&1 Duplicate subject name definition ; exit 1
	fi
	SUBJ="$ar"
	;;

    -days=* ) CERT_DAYS="${ar#*=}" ;;
    -out=* ) FN="${ar#*=}" ;;

    -rsa ) eval "mkkey() { openssl genrsa 3072 ; }" ;;
    -rsa=* ) eval "mkkey() { openssl genrsa '${ar#*=}' ; }" ;;
    -dsa ) eval "mkkey() { openssl dsaparam -genkey 3072 ; }" ;;
    -dsa=* ) eval "mkkey() { openssl dsaparam -genkey '${ar#*=}' ; }" ;;
    -ec ) eval "mkkey() { openssl ecparam -name prime256v1 -genkey ; }" ;;
    -ec=* ) eval "mkkey() { openssl ecparam -name '${ar#*=}' -genkey ; }" ;;

    -md4|-md5|-ripemd160|-sha|-sha1|-sha224|-sha256|-sha384|-sha512|-whirlpool)
	DGST=$ar ;;

    -v3=* ) [ "$V3OPTS" = "" ] && V3OPTS="$V3INIT"
	    V3OPTS="$V3OPTS
	    ${ar#*=}
	    "
	    ;;

    -v3xt=* )
	    [ "$V3OPTS" = "" ] && V3OPTS="$V3INIT"
	    V3EXTRAS="$V3EXTRAS
	    ${ar#*=}
	    "
	    ;;

    -v3ca ) [ "$V3OPTS" = "" ] && V3OPTS="$V3INIT"
	    V3OPTS="$V3OPTS
	    subjectKeyIdentifier=hash
	    authorityKeyIdentifier=keyid:always,issuer
	    basicConstraints = CA:TRUE
	    "
	    ;;

    -v3usr ) [ "$V3OPTS" = "" ] && V3OPTS="$V3INIT"
	    V3OPTS="$V3OPTS
	    basicConstraints = CA:FALSE
	    subjectKeyIdentifier=hash
	    authorityKeyIdentifier=keyid,issuer
	    "
	    ;;

    -*|*/*) echo >&2 "Unknown option: $ar" ; exit 1 ;;

    * ) if [ "$SUBJ" != "" ] ; then
	    echo >&1 Duplicate subject name definition ; exit 1
	fi
	SUBJ="/CN=$ar/" ; CN="$ar";;
    esac
done

[ -s "$FN" ] &&
    { echo ERROR: File $FN already exists ; exit 1 ; }

CAKEY="$(mkkey)"
CACERT="$(
openssl req -new -x509 $DGST -days "${CERT_DAYS:-3652}" \
    ${SUBJ:+-subj "$SUBJ"} \
    -key <(echo "$CAKEY") -config <(echo '
[req]
distinguished_name = req_distinguished_name
'"$V3OPTS"'
[ req_distinguished_name ]
organizationalUnitName = Organizational Unit Name
commonName = Common Name
'"$V3EXTRAS" )

)"

outp() {
    echo "$CACERT" | openssl x509 -subject -serial -dates
    if ! openssl no-pkey >/dev/null
    then echo "$CAKEY" | openssl pkey
    else echo "$CAKEY"
    fi
}

if [ "$FN" != '' ] ; then umask 077 ; outp > "$FN" ; else outp ; fi
