#!/bin/sh

D="${1:-localhost}" ; shift
L=$(pwd)

case "$1" in
-* ) ;;
"" ) ;;
* ) mkdir -p "$1" ; cd "$1" || exit ; shift ;;
esac

if faketime -h 2>/dev/null | grep -qi libfaketime
then ft() { faketime -f '1999-01-01 12:00:00' "$@" ; }
else ft() { "$@" ; }
fi

ft "$L"/mk-cert \
    -suca -v3 -rsa -alldays -san \
    -crlout="$D".crl \
    -pkcs12="$D".pfx \
    -keyout="$D".key \
    -caout="$D".ca.crt \
    -out="$D".crt \
    -subj-cn="$D" \
    "$@"
