#!/bin/bash

D="${1:-localhost}" ; shift
PATH="$PATH:$(pwd)"

case "$1" in
-* ) ;;
"" ) ;;
* ) mkdir -p "$1" ; cd "$1" || exit ; shift ;;
esac

mk-cert \
    -suca -v3 -rsa -alldays -san \
    -crlout="$D".crl \
    -pkcs12="$D".pfx \
    -keyout="$D".key \
    -caout="$D".ca.crt \
    -out="$D".crt \
    -cn="$D" \
    "$@"

for i in "$D".crl "$D".key "$D".ca.crt "$D".crt
do  [ -s "$i" ] && {
	sed $'s/$/\r/' < "$i" > "$i".tmp && mv "$i".tmp "$i"
    }
done
