#!/bin/bash
if [ ! -n "$BASH_VERSION" ];then exec bash "$0" "$@";else set +o posix;fi

NL='
'

for file
do
    DATA="$(cat "$file")"
    CERTPUB="$(echo "$DATA" | openssl x509 -pubkey -noout 2>/dev/null)"
    REQPUB="$(echo "$DATA" | openssl req -pubkey -noout 2>/dev/null)"
    PKEYPUB="$(echo "$DATA" | openssl pkey -pubout 2>/dev/null)"

    [ "$CERTPUB" != "" ] && CERTPUB="$(echo "$CERTPUB" | openssl md5 | awk '{print $2;}')"
    [ "$REQPUB" != "" ] && REQPUB="$(echo "$REQPUB" | openssl md5 | awk '{print $2;}')"
    [ "$PKEYPUB" != "" ] && PKEYPUB="$(echo "$PKEYPUB" | openssl md5 | awk '{print $2;}')"

    FIRSTCERTPUB="$CERTPUB"
    FIRSTPKEYPUB="$PKEYPUB"
    FIRSTREQPUB="$REQPUB"
    ISSU=
    CHAIN=""

    k=0
    while :
    do
	((k+=1))
	ITEM="$(echo "$DATA" | awk -v k=$k '/^-----BEGIN/ && k>1 {k--;next;} /^-----BEGIN/&& k {disp=1;} disp{print;} /^-----END/&&disp{disp=0;k--;}')"
	[ "$ITEM" = "" ] && break

	CERTPUB="$(echo "$ITEM" | openssl x509 -pubkey -noout 2>/dev/null)"
	REQPUB="$(echo "$ITEM" | openssl req -pubkey -noout 2>/dev/null)"
	PKEYPUB="$(echo "$ITEM" | openssl pkey -pubout 2>/dev/null)"

	[ "$CERTPUB" != "" ] && CERTPUB="$(echo "$CERTPUB" | openssl md5 | awk '{print $2;}')"
	[ "$PKEYPUB" != "" ] && PKEYPUB="$(echo "$PKEYPUB" | openssl md5 | awk '{print $2;}')"
	[ "$REQPUB" != "" ] && REQPUB="$(echo "$REQPUB" | openssl md5 | awk '{print $2;}')"

	if [ "$CERTPUB" != "" ]
	then
	    echo "$ITEM" | openssl x509 -noout -text -certopt no_sigdump,no_pubkey
	    [ "$CERTPUB" = "$FIRSTPKEYPUB" ] &&
		echo "    The file contains a private key that matches this certificate."

	    SUBJ="$(echo "$ITEM" | openssl x509 -subject_hash -noout 2>/dev/null)"
	    [ "$SUBJ" = "$ISSU" ] &&
		echo '    This certificate is the issuer for the previous one'

	    ISSU="$(echo "$ITEM" | openssl x509 -issuer_hash -noout 2>/dev/null)"

	    if [ "$SUBJ" = "$ISSU" ]
	    then
		if openssl verify -CAfile <(echo "$ITEM") <(echo "$ITEM") >/dev/null 2>&1
		then

		    if openssl verify -CAfile <(echo "$ITEM" ; echo "$CHAIN" ) <(echo "$DATA") >/dev/null 2>&1
		    then
			echo '    This self signed certificate successfully verifies the chain'
		    else
			echo '    This certificate is self signed'
		    fi

		else
		    echo "    This self signed certificate fails validation"
		fi
	    elif [ "$CERTPUB" != "$FIRSTCERTPUB" ]
	    then
		CHAIN="$CHAIN$NL$ITEM"
	    fi

	elif [ "$REQPUB" != "" ]
	then
	    echo "$ITEM" | openssl req -noout -text -reqopt no_sigdump,no_pubkey
	    [ "$REQPUB" = "$FIRSTCERTPUB" ] &&
		echo "    This request matches the first certificate"
	elif [ "$PKEYPUB" != "" -a "$PKEYPUB" = "$FIRSTCERTPUB" ]
	then :
	elif [ "$PKEYPUB" != "" ]
	then
	    echo "$ITEM" | openssl pkey -noout -text -pubout
	else
	    echo Item $k not identified
	fi
    done
done
